options:
  ppa:
    type: string
    default:
    description: PPA to add before installing weebl.
  ppa_key:
    type: string
    default:
    description: Key for PPA.
  weebl_name:
    type: string
    default:
    description: Name of this instance of Weebl (e.g. Production Weebl).
  extra_options:
    type: string
    default: ""
    description: Extra options to put in the systemd service file.
  username:
    type: string
    default: "CanonicalOilCiBot"
    description: Launchpad username of default admin user.
  email:
    type: string
    default: "oil-ci-bot@canonical.com"
    description: Email of default admin user, as registered in Lauchpad.
  uid:
    type: string
    default: "oil-ci-bot"
    description: User id of default admin user.
  apikey:
    type: string
    default: "74f937de4ea3244bdd4bc404a70d0d24a174"
    description: Random string of characters to enable API access.
