options:
  ppa:
    type: string
    default:
    description: PPA to add before installing weebl.
  ppa_key:
    type: string
    default:
    description: Key for PPA.
  weebl_name:
    type: string
    default:
    description: Name of this instance of Weebl (e.g. Production Weebl).
  weebl_url:
    type: string
    default:
    description: URL of this instance of Weebl.
  uuid:
    type: string
    default: 589d2dec-c1bb-49ad-b481-8e2833518f36
    description: Weebl update uuid (changing this value will trigger an update).
