options:
  ppa:
    type: string
    default:
    description: PPA to add before installing weebl.
  ppa_key:
    type: string
    default:
    description: Key for PPA.
  weebl_name:
    type: string
    default:
    description: Name of this instance of Weebl (e.g. Production Weebl).
