options:
  ppa:
    type: string
    default:
    description: PPA to add before installing weebl.
  ppa_key:
    type: string
    default:
    description: Key for PPA.
  weebl_name:
    type: string
    default:
    description: Name of this instance of Weebl (e.g. Production Weebl).
  extra_options:
    type: string
    default: ""
    description: Extra options to put in the systemd service file.
  username:
    type: string
    default: "CanonicalOilCiBot"
    description: Launchpad username of default admin user.
  email:
    type: string
    default: "oil-ci-bot@canonical.com"
    description: Email of default admin user, as registered in Lauchpad.
  uid:
    type: string
    default: "oil-ci-bot"
    description: User id of default admin user.
  apikey:
    type: string
    default: None
    description: Random string of characters to enable API access.
  debug_mode:
    type: boolean
    default: True
    description: A boolean that turns on/off debug mode.
  allowed_hosts:
    type: string
    default: '[]'
    description: A list of strings representing the host/domain names to serve.
