#!/usr/bin/env python3

import os
import yaml
import shlex
import socket
from datetime import datetime
from subprocess import check_output


with open("/etc/weebl/weebl.yaml") as f:
    weebl_data = yaml.load(f.read())
now = datetime.now().strftime("%F_%H-%M-%S")
out = "weebl_db_backup_{}_{}".format(socket.gethostname(), now)
cmd = ("PGPASSWORD={password} pg_dump -h {host} -U {user} -p {port} -x -F "
       "t {database} > {output}".format(**weebl_data['database'], output=out))
check_output(shlex.split(cmd))
juju_ip, _, weebl_ip, __ = os.environ['SSH_CONNECTION'].split(' ')
print("Database dumped to '{}' on {}".format(output, weebl_ip))

# TODO: scp $OUTPUT to $JUJU_IP
