#!/usr/bin/env python3

from charms.layer.weebl import utils
from charmhelpers.core import hookenv
from charms.layer.weebl.constants import WEEBL_PKG

config = hookenv.config()
utils.install_deb(WEEBL_PKG, config)
utils.fix_bundle_dir_permissions()
utils.cmd_service('restart', 'nginx', hookenv)
